### ISSUE TITLE
Annotate associations using & Intersection

### ISSUE THREAD

**Issue by raul338** [dereuromark/cakephp-ide-helper#133]
Maybe it should annotate like this
```php
/**
 * @property \App\Model\Table\BooksTable&\Cake\ORM\Association\HasMany $Books
 */
class AuthorsTable extends Table
{
    // ....
    $this->Books->link($book, [$author1, $author2]);
}
```
With `|` phpstan throws that BooksTable does not have a method `link`, changing to intersection fixes that

**Comment by dereuromark** [comment]
You have to raise this mainly for bake and core defaults.
If so we can also adjust here
@ADmad what do u think?

**Comment by raul338** [comment]
PR Open

**Comment by Harfusha** [comment]
Hello, i was trying to resolve errors caused by this with phpstan, but they told me that this is wrong.
https://github.com/phpstan/phpstan/issues/11399

VScode is working fine with this annotations, but when i try to call method on associated model, then phpstan is throwing these errors.

- '#Cannot call method where\(\) on mixed\.#'
- '#Cannot call method toArray\(\) on mixed\.#'
- '#Cannot call method first\(\) on mixed\.#'
- '#Cannot call method contain\(\) on mixed\.#'
- '#Cannot call method order\(\) on mixed\.#'
- '#Cannot call method find\(\) on mixed\.#'
- '#Cannot call method limit\(\) on mixed\.#'

(This is what i use: $this->Users->Accounts->find()->where(CONDITIONS)->toArray() )

**Comment by dereuromark** [comment]
What would be the correct annotation here?
The current one is mainly also used for compatibility with the IDE and thus the developer.

**Comment by Harfusha** [comment]
> Intersection type cannot consist of two classes. That's not possible in PHP. An intersection type can consist of one class and one or more interfaces; or of two or more interfaces.

> But given you only have classes involved, and not interfaces, and also that __call is involved, I assume you're not actually looking for intersection types, but instead for @mixin: https://phpstan.org/writing-php-code/phpdocs-basics#mixins

But problem with mixins is that IDE doesnt lint their methods, so maybe it is combination of those two annotations to satisfy IDE and PHPStan

**Comment by dereuromark** [comment]
Feel free to propose a solution that works
